# Generated by Django 6.0.1 on 2026-01-12 06:17

import django.db.models.deletion
import learning_assistant.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to=learning_assistant.models.document_upload_path)),
                ('file_type', models.CharField(choices=[('pdf', 'PDF Document'), ('word', 'Word Document'), ('text', 'Text File'), ('image', 'Image')], max_length=20)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('extracted_text', models.TextField(blank=True)),
                ('page_count', models.PositiveIntegerField(default=0)),
                ('is_indexed', models.BooleanField(default=False)),
                ('chunk_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('summary_type', models.CharField(choices=[('brief', 'Brief Summary'), ('detailed', 'Detailed Summary'), ('bullet', 'Bullet Points')], max_length=20)),
                ('word_count', models.PositiveIntegerField(default=0)),
                ('model_used', models.CharField(blank=True, max_length=100)),
                ('generation_time', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='learning_assistant.document')),
            ],
            options={
                'verbose_name': 'Summary',
                'verbose_name_plural': 'Summaries',
                'ordering': ['-created_at'],
            },
        ),
    ]
