# Generated by Django 6.0.1 on 2026-01-14 10:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_assistant', '0002_quiz_quizquestion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FlashcardSet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('card_count', models.PositiveIntegerField(default=10)),
                ('cards_studied', models.PositiveIntegerField(default=0)),
                ('cards_mastered', models.PositiveIntegerField(default=0)),
                ('last_studied_at', models.DateTimeField(blank=True, null=True)),
                ('model_used', models.CharField(blank=True, max_length=100)),
                ('generation_time', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcard_sets', to='learning_assistant.document')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcard_sets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Flashcard Set',
                'verbose_name_plural': 'Flashcard Sets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('front', models.TextField(help_text='The concept, term, or question')),
                ('back', models.TextField(help_text='The explanation, definition, or answer')),
                ('priority', models.PositiveIntegerField(choices=[(1, 'Critical'), (2, 'Very Important'), (3, 'Important'), (4, 'Helpful'), (5, 'Supplementary')], default=3, help_text='1 = most important, 5 = least important')),
                ('is_mastered', models.BooleanField(default=False)),
                ('times_reviewed', models.PositiveIntegerField(default=0)),
                ('order', models.PositiveIntegerField(default=0)),
                ('flashcard_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='learning_assistant.flashcardset')),
            ],
            options={
                'verbose_name': 'Flashcard',
                'verbose_name_plural': 'Flashcards',
                'ordering': ['priority', 'order'],
            },
        ),
    ]
