# Generated by Django 6.0.1 on 2026-01-15 08:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_assistant', '0003_flashcardset_flashcard'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Flowchart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('node_count', models.PositiveIntegerField(default=0)),
                ('edge_count', models.PositiveIntegerField(default=0)),
                ('model_used', models.CharField(blank=True, max_length=100)),
                ('generation_time', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flowcharts', to='learning_assistant.document')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flowcharts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Flowchart',
                'verbose_name_plural': 'Flowcharts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FlowchartEdge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_node', models.CharField(help_text='Source node_id', max_length=50)),
                ('to_node', models.CharField(help_text='Target node_id', max_length=50)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('flowchart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges', to='learning_assistant.flowchart')),
            ],
            options={
                'verbose_name': 'Flowchart Edge',
                'verbose_name_plural': 'Flowchart Edges',
            },
        ),
        migrations.CreateModel(
            name='FlowchartNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('node_id', models.CharField(help_text='String identifier for connections', max_length=50)),
                ('label', models.CharField(max_length=255)),
                ('node_type', models.CharField(choices=[('start', 'Start'), ('end', 'End'), ('concept', 'Concept'), ('action', 'Action'), ('decision', 'Decision')], default='concept', max_length=20)),
                ('position_x', models.FloatField(blank=True, null=True)),
                ('position_y', models.FloatField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('flowchart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='learning_assistant.flowchart')),
            ],
            options={
                'verbose_name': 'Flowchart Node',
                'verbose_name_plural': 'Flowchart Nodes',
                'ordering': ['order'],
            },
        ),
    ]
