# Generated by Django 6.0.1 on 2026-02-16 10:34

import django.db.models.deletion
import learning_assistant.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_assistant', '0005_answer_sheet_evaluation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('script', models.TextField(blank=True, help_text='Full conversation script between hosts')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to=learning_assistant.models.podcast_upload_path)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('model_used', models.CharField(blank=True, max_length=100)),
                ('generation_time', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='podcasts', to='learning_assistant.document')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='podcasts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Podcast',
                'verbose_name_plural': 'Podcasts',
                'ordering': ['-created_at'],
            },
        ),
    ]
